src/Entity/Abonnement.php
<?php

namespace App\Entity;

use App\Repository\AbonnementRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AbonnementRepository::class)
 */
class Abonnement
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var \User
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_user", referencedColumnName="id_user")
     * })
     */
    private $id_user;

    /**
     * @var \Jeu
     * @ORM\ManyToOne(targetEntity=Jeu::class)
     * @ORM\JoinColumn(name="id_jeu", referencedColumnName="Id_Jeu")
     * })
     */
    private $id_jeu;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(?User $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getIdJeu(): ?Jeu
    {
        return $this->id_jeu;
    }

    public function setIdJeu(?Jeu $id_jeu): self
    {
        $this->id_jeu = $id_jeu;

        return $this;
    }
}

src/Entity/Skin.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Cache\Adapter\ArrayAdapter;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Skin
 *
 * @ORM\Table(name="skin", indexes={@ORM\Index(name="Id_champ", columns={"Id_champ"})})
 * @ORM\Entity
 */
class Skin
{
    /**
     * @var int
     *
     * @ORM\Column(name="Id_skin", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idSkin;

    /**
     * @var string
     * @Assert\NotBlank()
     * @ORM\Column(name="image_skin", type="string", length=255, nullable=false)
     */
    private $imageSkin;

    /**
     * @var \Champion
     * @Assert\NotBlank()
     * @ORM\ManyToOne(targetEntity="Champion")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="Id_Champ", referencedColumnName="Id_Champ")
     * })
     */
    private $idChamp;

    public function getIdSkin(): ?int
    {
        return $this->idSkin;
    }

    public function getImageSkin()
    {
        return $this->imageSkin;
    }

    public function setImageSkin($imageSkin)
    {
        $this->imageSkin = $imageSkin;

        return $this;
    }

    public function getIdChamp(): ?Champion
    {
        return $this->idChamp;
    }

    public function setIdChamp(Champion $idChamp): self
    {
        $this->idChamp = $idChamp;

        return $this;
    }
    public function getImagePath(): string
    {
        return 'uploads/skins/'.$this->getImageSkin();
    }

}

src/Controller/AdminImageController.php
<?php

namespace App\Controller;

use App\Entity\Image;
use App\Form\ImageType;
use App\Repository\ImageRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;

/**
 * @Route("/admin/image")
 */
class AdminImageController extends AbstractController
{
    /**
     * @Route("/", name="app_admin_image_index", methods={"GET"})
     */
    public function index(EntityManagerInterface $entityManager): Response
    {
        $images = $entityManager
            ->getRepository(Image::class)
            ->findAll();

        return $this->render('admin_image/index.html.twig', [
            'images' => $images,
        ]);
    }

    /**
     * @Route("/new", name="app_admin_image_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager,ImageRepository $repimg, TranslatorInterface $translate): Response
    {
        $image = new Image();
        $form = $this->createForm(ImageType::class, $image);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file=$image->getUrlImage();
            $idimg=$repimg->maxidimg();
            // On boucle sur les images
            // On génère un nouveau nom de fichier
            $fichier = $idimg.'.'.$file->guessExtension();

            // On copie le fichier dans le dossier uploads
            try {
                $file->move(
                    $this->getParameter('images_directory'),
                    $fichier
                );
            } catch (FileException $e) { new Response($e->getMessage());}

            // On stocke l'image dans la base de données (son nom)

            $entityManager=$this->getDoctrine()->getManager();
            $image->setUrlImage($fichier);
            $entityManager->persist($image);
            $entityManager->flush();


            return $this->redirectToRoute('app_admin_image_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin_image/new.html.twig', [
            'image' => $image,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{idImage}", name="app_admin_image_show", methods={"GET"})
     */
    public function show(Image $image): Response
    {
        return $this->render('admin_image/show.html.twig', [
            'image' => $image,
        ]);
    }

    /**
     * @Route("/{idImage}/edit", name="app_admin_image_edit", methods={"GET", "POST"})
     */
    public function edit(Image $img,Request $request, Image $image, EntityManagerInterface $entityManager,ImageRepository $repimg, TranslatorInterface $translate): Response
    {
        $form = $this->createForm(ImageType::class, $image);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file=$image->getUrlImage();
            $idimg=$img->getIdImage();

            // On génère un nouveau nom de fichier
            $fichier = $idimg.'.'.$file->guessExtension();

            // On copie le fichier dans le dossier uploads
            try {
                $file->move(
                    $this->getParameter('images_directory'),
                    $fichier
                );
            } catch (FileException $e) { new Response($e->getMessage());}
            $entityManager=$this->getDoctrine()->getManager();
            $image->setUrlImage($fichier);
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_image_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin_image/edit.html.twig', [
            'image' => $image,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{idImage}", name="app_admin_image_delete", methods={"POST"})
     */
    public function delete(Request $request, Image $image, EntityManagerInterface $entityManager, TranslatorInterface $translate): Response
    {

        if ($this->isCsrfTokenValid('delete'.$image->getIdImage(), $request->request->get('_token'))) {
            $file=$image->getUrlImage();
            unlink($this->getParameter('images_directory').'/'.$file);
            $entityManager->remove($image);
            $entityManager->flush();

        }

        return $this->redirectToRoute('app_admin_image_index', [], Response::HTTP_SEE_OTHER);
    }
    /**
     * @Route("/", name="app_admin_image_index", methods={"GET", "POST"})
     */
    public function search(Request $request , ImageRepository $repimage)
    {
        $em=$this->getDoctrine()->getManager();
        $image=$em->getRepository(Image::class)->findAll();
        if ($request->isMethod("POST")) {
            $nom = $request->get('nom');
            $image = $repimage->search($nom);
        }
        return $this->render('admin_image/index.html.twig', [
            'images' => $image,
        ]);

    }
}

templates/admin_image/_delete_form.html.twig
<form method="post" action="{{ path('app_admin_image_delete', {'idImage': image.idImage}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ image.idImage) }}">
    <button class="btn btn-outline-success">Delete</button>
</form>

templates/admin_image/_form.html.twig
{{ form_start(form , {
    attr:{
        'novalidate':'novalidate'
    }
}) }}

    {{ form_row(form.urlImage ,{
        attr:{
            'maxlength':'255'
        }
    }) }}
    {{ form_row(form.idJeu) }}

    <button class="btn btn-outline-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/admin_image/edit.html.twig
{% extends 'Admin_base.html.twig' %}

{% block title %}Edit Image{% endblock %}

{% block content %}
    <h1>Edit Image</h1>

    {{ include('admin_image/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_admin_image_index') }}" class="btn btn-outline-info">back to list</a>

    {{ include('admin_image/_delete_form.html.twig') }}
{% endblock %}

templates/admin_image/index.html.twig
{% extends 'Admin_base.html.twig' %}

{% block title %}Image index{% endblock %}
{% block top %}
    {% include 'skeleton/admin_search.html.twig' %}
{% endblock %}
{% block content %}
    <h1>Image index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>IdImage</th>
                <th>UrlImage</th>
                <th>idJeu</th>
                <th>actions</th>

            </tr>
        </thead>
        <tbody>
        {% for image in images %}
            <tr>
                <td>{{ image.idImage }}</td>
                <td><img class="show-img" src="{{ asset(image.imagePath) }}" alt="" width="300" height="200">
                    <style>
                        show-img {
                            width: 100%;
                            height: auto;
                        }
                    </style>
                </td>
                <td>   {{ image.idJeu }}</td>
                <td>
                     <a href="{{ path('app_admin_image_show', {'idImage': image.idImage}) }}"class="btn btn-outline-info">show</a>
                    <a href="{{ path('app_admin_image_edit', {'idImage': image.idImage}) }}" class="btn btn-outline-dark">edit</a>

                </td>

            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_admin_image_new') }}"class="btn btn-outline-success">Create new</a>
{% endblock %}

templates/admin_image/new.html.twig
{% extends 'Admin_base.html.twig' %}

{% block title %}New Image{% endblock %}

{% block content %}
    <h1>Create new Image</h1>

    {{ include('admin_image/_form.html.twig') }}

     <a href="{{ path('app_admin_image_index') }}"class="btn btn-outline-info">back to list</a>
{% endblock %}

templates/admin_image/show.html.twig
{% extends 'Admin_base.html.twig' %}

{% block title %}Image{% endblock %}

{% block content %}
    <h1>Image</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>IdImage</th>
                <td>{{ image.idImage }}</td>
            </tr>
            <tr>
                <th>UrlImage</th>
                <td>
                    <img class="show-img" src="{{ asset(image.imagePath) }}" width="460" height="345" alt="">
                    <style>
                        show-img {
                            width: 100%;
                            height: auto;
                        }
                    </style>
                </td>
            </tr>
        <tr>
                <th> idJeu</th>
            <td>{{ image.idJeu }}</td>

        </tr>
        </tbody>
    </table>
    <a href="{{ path('app_admin_image_index') }}"class="btn btn-outline-info">back to list</a>

    <a href="{{ path('app_admin_image_edit', {'idImage': image.idImage}) }}" class="btn btn-outline-dark">edit</a>

    {{ include('admin_image/_delete_form.html.twig') }}


{% endblock %}