src/Entity/Joueur.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Joueur
 *
 * @ORM\Table(name="joueur", indexes={@ORM\Index(name="id_equipe", columns={"id_equipe"}), @ORM\Index(name="user_joueur", columns={"id_user"})})
 * @ORM\Entity
 */
class Joueur
{
    /**
     * @var int
     *
     * @ORM\Column(name="id_Joueur", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idJoueur;

    /**
     * @var string
     *@Assert\NotBlank
     * @ORM\Column(name="nom_Joueur", type="string", length=50, nullable=false)
     */
    private $nomJoueur;

    /**
     * @var string
     *@Assert\NotBlank
     * @ORM\Column(name="rang_Joueur", type="string", length=50, nullable=false)
     */
    private $rangJoueur;

    /**
     * @var string
     *@Assert\NotBlank
     * @ORM\Column(name="Pseaudo_Joueur", type="string", length=25, nullable=false)
     */
    private $pseaudoJoueur;

    /**
     * @var \User
     *@Assert\NotBlank
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_user", referencedColumnName="id_user")
     * })
     */
    private $idUser;

    /**
     * @var \Equipe
     *@Assert\NotBlank
     * @ORM\ManyToOne(targetEntity="Equipe")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_equipe", referencedColumnName="id_Equipe")
     * })
     */
    private $idEquipe;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Tel;

    public function getIdJoueur(): ?int
    {
        return $this->idJoueur;
    }

    public function getNomJoueur(): ?string
    {
        return $this->nomJoueur;
    }

    public function setNomJoueur(string $nomJoueur): self
    {
        $this->nomJoueur = $nomJoueur;

        return $this;
    }

    public function getRangJoueur(): ?string
    {
        return $this->rangJoueur;
    }

    public function setRangJoueur(string $rangJoueur): self
    {
        $this->rangJoueur = $rangJoueur;

        return $this;
    }

    public function getPseaudoJoueur(): ?string
    {
        return $this->pseaudoJoueur;
    }

    public function setPseaudoJoueur(string $pseaudoJoueur): self
    {
        $this->pseaudoJoueur = $pseaudoJoueur;

        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->idUser;
    }

    public function setIdUser(?User $idUser): self
    {
        $this->idUser = $idUser;

        return $this;
    }

    public function getIdEquipe(): ?Equipe
    {
        return $this->idEquipe;
    }

    public function setIdEquipe(?Equipe $idEquipe): self
    {
        $this->idEquipe = $idEquipe;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(?string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }


}

src/Controller/ClientJoueurController.php
<?php

namespace App\Controller;
use App\Entity\Defi;
use App\Entity\Equipe;
use App\Entity\Jeu;
use App\Entity\Joueur;
use App\Entity\User;
use App\Form\JoueurType;
use App\Repository\DefiRepository;
use App\Repository\DetailsDefiRepository;
use App\Repository\JoueurRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Exception\ExceptionInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;
use Twilio\Rest\Client;

class ClientJoueurController extends AbstractController
{
    /**
     * @Route("/client/joueur/all", name="app_admin_joueur_mobile_index", methods={"GET"})
     * @throws ExceptionInterface
     */
    public function Mobile_Index(EntityManagerInterface $entityManager,NormalizerInterface $Normalizer): JsonResponse
    {
        $Joueur = $entityManager
            ->getRepository(Joueur::class)
            ->findAll();

        $s=new Serializer([new ObjectNormalizer()]);
        $formatted=$s->normalize($Joueur);
        return new JsonResponse($formatted);
    }
    /**
     * @Route("/client/joueur", name="app_client_joueur")
     */
    public function index(): Response
    {
        return $this->render('client_joueur/index.html.twig', [

        ]);
    }
    /**
     * @Route("/client/joueur/new", name="app_client_joueur_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager,UserRepository $rep,JoueurRepository $res): Response
    {
        $account_sid = 'AC05bff866418daf2f594de475cdd43ee8';
        $auth_token = '87e10d3329e3e895db98826290377bf5';

        $username=$this->getUser()->getUsername();

        /** @var User $user */
        $user = $rep->findOneBy(['username'=>$username]);
        $us = $res->Verify($user->getIdUser());

//        if($us){
//            $jr = $res->findOneBy(['idUser'=>$user]);
//            $joueurs = $res->findBy(['idEquipe'=>$jr->getIdEquipe()]);
//            return $this->redirectToRoute('app_client_equipe', [
//                'joueursParEquipe'=>$joueurs
//            ], Response::HTTP_SEE_OTHER);
//        }
        if($us!=null){
            return $this->redirectToRoute('app_client_equipe', [], Response::HTTP_SEE_OTHER);
        }

        $joueur = new Joueur();
        $form = $this->createForm(JoueurType::class, $joueur);
        $form->handleRequest($request);
        $twilio_number = '+18623977436';
        $client = new Client($account_sid, $auth_token);
        if ($form->isSubmitted() && $form->isValid()) {

            $joueur->setIdUser($user);
            $entityManager->persist($joueur);
            $entityManager->flush();
            $client->messages->create(
            // Where to send a text message (your cell phone?)
                '+216'.$joueur->getTel(),
                array(
                    'from' => $twilio_number,
                    'body' => 'Welcome '.$joueur->getNomJoueur().' Enjoy your games with  '.$joueur->getIdEquipe()->getNomEquipe()
                )
            );
            return $this->redirectToRoute('app_client_equipe', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('client_joueur/index.html.twig', [
            'joueur' => $joueur,
            'formA' => $form->createView(),
        ]);
    }

    /**
     * @Route("/client/joueur/{idJoueur}", name="app_client_joueur_show", methods={"GET"})
     */
    public function show(Joueur $joueur,DetailsDefiRepository $rep ,DefiRepository $res): Response
    {
        $matchs =$rep
            ->TopThree();
        $datedb = $rep->DateDataBase() ;
        $Upcoming = $rep->Upcoming() ;
        $Match_curent =$rep->Live();
        $defis = $res->findByThree();

        return $this->render('client_joueur/JoueurProfile.html.twig', [
            'joueur' => $joueur,
            'matchs' => $matchs,
            'dbs' => $datedb,
            'ups' => $Upcoming,
            'live'=>$Match_curent,
            'defis' => $defis
        ]);
    }
    /**
     * @Route("/client/joueur/new/AddJoueurs", name="new_Joueur_mobile" )
     */
    public function addJoueur(Request $request,NormalizerInterface $normalizer,UserRepository $rep): JsonResponse
    {
        $em=$this->getDoctrine()->getManager();
        $joueur= new Joueur();

        $joueur->setNomJoueur($request->get('nomJoueur'));
        $joueur->setPseaudoJoueur($request->get('pseaudoJoueur'));
        $joueur->setRangJoueur($request->get('rangJoueur'));
        $joueur->setTel($request->get('Tel'));

        $twilio_number = '+18623977436';


        $account_sid = 'AC05bff866418daf2f594de475cdd43ee8';
        $auth_token = '87e10d3329e3e895db98826290377bf5';
        $client = new Client($account_sid, $auth_token);


        $id_equipe = $request->get('idEquipe');

        $e=$this->getDoctrine()->getRepository(Equipe::class)->findOneBy(['idEquipe'=>$id_equipe]);
        $username=$request->get('idUser');

        /** @var User $user */
        $user = $rep->findOneBy(['idUser'=>$username]);
        $joueur->setIdEquipe($e);
        $joueur->setIdUser($user);
        $client->messages->create(
        // Where to send a text message (your cell phone?)
            '+216'.$joueur->getTel(),
            array(
                'from' => $twilio_number,
                'body' => 'Welcome '.$joueur->getNomJoueur().' Enjoy your games with  '.$joueur->getIdEquipe()->getNomEquipe()
            )
        );
//        dd($joueur);
        $em->persist($joueur);
        $em->flush();
//    $jsoncontent=$normalizer->normalize($jeux,'json',['groups'=>'post:read']);
//    return new Response(json_encode($jsoncontent));
        $s=new Serializer([new ObjectNormalizer()]);
        $formatted=$s->normalize($joueur);

        return new JsonResponse($formatted);


    }
}

templates/client_joueur/index.html.twig
{% extends 'base.html.twig' %}
{% block content %}

    <div class="nk-gap-1"></div>
    <div class="container">
        <ul class="nk-breadcrumbs">


            <li><a href="index.html">Home</a></li>


            <li><span class="fa fa-angle-right"></span></li>

            <li><a href="store.html">Teams</a></li>

            <li><span class="fa fa-angle-right"></span></li>

            <li><span>Add new Team</span></li>

        </ul>
    </div>
    <div class="nk-gap-1"></div>
    <!-- END: Breadcrumbs -->




    <div class="container">

        <div class="nk-store nk-store-checkout">
            <h3 class="nk-decorated-h-2"><span><span class="text-main-1">Team</span> Details</span></h3>

            <!-- START: Billing Details -->
            <div class="nk-gap"></div>
            {{ form_start(formA,  { 'attr': { 'class': 'demo-nk-form', 'data-parsley-validate': null } } ) }}

            <div class="row vertical-gap">
                <div class="col-lg-6">
                    <div class="row vertical-gap">
                        <div class="col-sm-6">
                            <label for="fname">Nom du joueur  <span class="text-main-1">*</span>:</label>

                            {{ form_widget(formA.nomJoueur,{'attr':{'class':'form-control','name':'fname','id':'fname'}}) }}
                            <label for="fname">Telephone  <span class="text-main-1">*</span>:</label>

                            {{ form_widget(formA.tel,{'attr':{'class':'form-control','name':'fname','id':'fname'}}) }}
                        </div>


                    </div>


                    <div class="nk-gap-1"></div>

                </div>
                <div class="col-lg-6">
                    <label for="address">Equipe  <span class="text-main-1">*</span>:</label>

                    {{form_widget(formA.idEquipe,{'attr':{'class':'form-control ','name':'country','id':'country-sel'}}) }}
                    {{form_widget(formA.idUser,{'attr':{'class':'form-control ','name':'country','id':'country-sel','hidden':true}}) }}
                    <div class="nk-gap-1"></div>
                    <div class="nk-gap-1"></div>
                    <label for="city">Rang du Joueur <span class="text-main-1">*</span>:</label>

                    {{ form_widget(formA.rangJoueur,{'attr':{'class':'form-control ','name':'city','id':'city'}}) }}
                    <div class="nk-gap-1"></div>
                    <label for="city">Pseaudo<span class="text-main-1">*</span>:</label>

                    {{ form_widget(formA.pseaudoJoueur,{'attr':{'class':'form-control ','name':'city','id':'city'}}) }}
                    <div class="nk-gap-1"></div>
                </div>
            </div>


            <div class="nk-gap-3"></div>
            <h3 class="nk-decorated-h-2"><span><span class="text-main-1">ADD</span> Team</span></h3>
            <div class="nk-gap"></div>

            <!-- END: Order Products -->

            <div class="nk-gap-2"></div>
            <button class="nk-btn nk-btn-rounded nk-btn-color-main-1">{{ button_label|default('Save') }}</button>
        </div>
    </div> {{ form_end(formA) }}
    <div class="nk-gap-2"></div>
{% endblock %}